# Generated by Django 2.2.3 on 2019-07-08 05:50

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30, null=True, verbose_name='Patient name')),
                ('Sex', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=10, null=True, verbose_name='sex')),
                ('Dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('Age', models.IntegerField()),
                ('Contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Contact')),
                ('Address', models.CharField(max_length=200, null=True, verbose_name='Address')),
                ('Email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('Blood_group', models.CharField(blank=True, choices=[('ab+', 'AB+'), ('ab-', 'AB-'), ('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o-', 'O-'), ('o+', 'O+')], max_length=4, verbose_name='blood group')),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Patient name')),
                ('N', models.IntegerField()),
            ],
        ),
    ]
