# Generated by Django 2.2.3 on 2019-07-11 15:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30, null=True, verbose_name='doctor name')),
                ('Sex', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=10, null=True, verbose_name='sex')),
                ('Contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Contact')),
                ('Email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('Spec', models.CharField(blank=True, choices=[('physician', 'physician'), ('orthopedic', 'orthopedic'), ('cardiologist', 'cardiologist'), ('pediatrician', 'pediatrician')], max_length=10, null=True, verbose_name='specification')),
            ],
        ),
        migrations.CreateModel(
            name='receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recp_name', models.CharField(max_length=30, null=True, verbose_name='Receiptionist name')),
                ('Sex', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=10, null=True, verbose_name='sex')),
                ('Contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Contact')),
                ('Email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
                ('pa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Password')),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='N',
        ),
        migrations.RemoveField(
            model_name='report',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='Password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='report',
            name='Date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='report',
            name='Hemoglobin',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)], verbose_name='Hemoglobin'),
        ),
        migrations.AddField(
            model_name='report',
            name='Neutrophils',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(80), django.core.validators.MinValueValidator(0)], verbose_name='Neutrophil'),
        ),
        migrations.AddField(
            model_name='report',
            name='basophils',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='basophils'),
        ),
        migrations.AddField(
            model_name='report',
            name='eosinophils',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='eosinophils'),
        ),
        migrations.AddField(
            model_name='report',
            name='lymphocytes',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)], verbose_name='lymphocytes'),
        ),
        migrations.AddField(
            model_name='report',
            name='monocytes',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='monocytes'),
        ),
        migrations.AddField(
            model_name='report',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.patient'),
        ),
        migrations.AddField(
            model_name='report',
            name='platelets',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(400000), django.core.validators.MinValueValidator(0)], verbose_name='rbc'),
        ),
        migrations.AddField(
            model_name='report',
            name='rbc',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)], verbose_name='rbc'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female'), ('Others', 'others')], max_length=10, null=True, verbose_name='sex'),
        ),
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True, verbose_name='Date')),
                ('identity', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=30, null=True, verbose_name='name')),
                ('Doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(null=True, verbose_name='Date')),
                ('ndays', models.IntegerField(blank=True, null=True, verbose_name='ndays')),
                ('room', models.IntegerField(blank=True, choices=[(500, 'general'), (1000, 'icu')], null=True, verbose_name='room')),
                ('report', models.IntegerField(blank=True, null=True, verbose_name='report')),
                ('fee', models.IntegerField(blank=True, null=True, verbose_name='fee')),
                ('operation', models.IntegerField(blank=True, default=0, null=True, verbose_name='operation')),
                ('tot', models.IntegerField(blank=True, default=0, null=True, verbose_name='total')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.patient')),
            ],
        ),
    ]
