# Generated by Django 2.2.3 on 2019-07-11 18:02

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190711_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('Contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Contact')),
                ('Address', models.CharField(max_length=200, null=True, verbose_name='Address')),
            ],
        ),
    ]
