# Generated by Django 2.2.3 on 2019-07-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ambulance'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Sex',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], max_length=10, null=True, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Spec',
            field=models.CharField(blank=True, choices=[('physician', 'physician'), ('orthopedic', 'orthopedic'), ('cardiologist', 'cardiologist'), ('pediatrician', 'pediatrician')], max_length=15, null=True, verbose_name='specification'),
        ),
    ]
